# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  default:
    cmd: task --list-all

  generate:
    cmd: templ generate

  clean:
    cmd: if [ -d ./out ]; then rm -r ./out; fi

  build:
    deps:
      - clean
      - generate
    cmd: go build -o out/music-collection main.go

  run:
    deps:
      - build
    cmds:
      - defer: { task: clean }
      - ./out/music-collection

  dev:
    cmds:
      - defer: { task: clean }
      - air