# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  default:
    cmd: task --list-all

  build:
    cmds:
      - templ generate
      - go build -o out/music-collection main.go

  run:
    deps:
      - build
    cmd: ./out/music-collection
